---
- name: Ensure all packages are up-to-date
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install the dnf-automatic package
  ansible.builtin.yum:
    name: dnf-automatic
    state: present

- name: Copy dnf-automatic configuration file in place
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: 0644

- name: Enable and start dnf-automatic timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: yes
    state: started
